version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker-compose.php.dockerfile
    volumes:
      - ./:/var/www
      - ./docker-compose.httpd.conf:/etc/apache2/httpd.conf
    working_dir: /var/www
    ports:
      - 8080:8080
